name: Release SiteFlow (Installer & Portable)

on:
  push:
    tags:
      - 'v*'

# دادن دسترسی‌های لازم برای ساخت ریلیز و آپلود فایل‌ها
permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24' # آپدیت به نود ۲۴ برای حل اخطار دپریکیت شدن نود ۲۰
        cache: 'npm'

    - name: Install Dependencies
      run: npm install

    - name: Build Electron App for Windows
      run: npm run dist:win
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # آپلود دقیق فایل‌ها از پوشه dist-desktop که در پکیج جی‌سان تعریف شده
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist-desktop/*.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
